# Generated by Django 4.2.4 on 2023-08-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
