# Generated by Django 4.2.3 on 2023-08-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_options_alter_scope_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='article', through='articles.Scope', to='articles.tag'),
        ),
    ]
